### ISSUE TITLE
pingAllCandidates called with no candidate pairs

### ISSUE THREAD

**Issue by gbrian** [m1k1o/neko#105]
Hi there,

Sorry can't connect to neko.
Running neko from https://hub.docker.com/r/m1k1o/neko

Container output:
```
neko_1        | 2021-12-03 12:03:04,986 DEBG 'neko' stdout output:
neko_1        | 12:03PM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc subsystem=ice
```

docker-compose.yaml

```
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "1080:8080"
      - "62000-62100:52000-52100/udp"
    environment:
      NEKO_SCREEN: '1920x1080@30'
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_NAT1TO1: 192.168.0.13
```

Any idea?

**Comment by gbrian** [comment]
My bad!
Wrong UDP ports definition. See final version

docker-compose.yaml

```
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "1080:8080"
      - "62000-62100:62000-62100/udp"    <-------- HERE
    environment:
      NEKO_SCREEN: '1920x1080@30'
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 62000-62100.                    <--------- HERE
      NEKO_NAT1TO1: 192.168.0.13
```
