### ISSUE TITLE
[Feature request] Helm chart for k8s deployment

### ISSUE THREAD

**Issue by akashsharma95** [m1k1o/neko#118]
It would be nice to have helm chart to deploy neko to k8s cluster

**Comment by mbattista** [comment]
Do you have a k8s cluster for testing?
https://kompose.io can convert docker-compose files into helm charts, but I have not enough knowledge about helm charts or kubernetes to know if the resulting chart is any good.

I attached the helm charts created by https://github.com/kubernetes/kompose/releases/tag/v1.26.0 if you want to try it. (and wow, github does not support the .yaml file extension, so you probably need to remove the .txt)
[neko-deployment.yaml.txt](https://github.com/m1k1o/neko/files/7699963/neko-deployment.yaml.txt)
[neko-service.yaml.txt](https://github.com/m1k1o/neko/files/7699964/neko-service.yaml.txt)

**Comment by anthr76** [comment]
I'd be willing to test this, but wow. Are all those ports nessecary?

**Comment by mbattista** [comment]
https://neko.m1k1o.net/#/getting-started/?id=why-so-many-ports

For testing probably not. Later they could be necessary, depending on how many viewers you want to have.

**Comment by m1k1o** [comment]
There has been an attempt to implement [single port ice using tcp and udp mux](https://github.com/m1k1o/neko/commit/c97b1fc4541caabf6b00331d081b02d2f9c58751) (#106), that allows using one port instead. This feature is not properly tested yet and only experimental.

We can use TCP mux and/or UDP mux, example:

```yaml
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "8081:8081/tcp"
      - "8082:8082/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_TCPMUX: 8081
      NEKO_UDPMUX: 8082
      NEKO_ICELITE: 1
```
