### ISSUE TITLE
Document config file

### ISSUE THREAD

**Issue by e00E** [m1k1o/neko#142]
The documentation mentions

> You can mount YAML config file to docker container on this path /etc/neko/neko.yaml and store your configuration there.

However I cannot find any documentation on the format of the config file. There should be an example config file that contains all the options.

**Comment by m1k1o** [comment]
All the keys from [arguments](https://neko.m1k1o.net/#/getting-started/configuration?id=agruments), that can be viewed in program's help output.

Example, setting `nat1to1` variable:
- As env variable: `NEKO_NAT1TO1=<ip>`
- As argument: `--nat1to1=<ip>`
- In YAML config file:
```yaml
nat1to1: <ip>
```

So the config would look like this (taken just some of the arguments):

```yaml
# audio bitrate in kbit/s
audio_bitrate: 128

# video bitrate in kbit/s
video_bitrate: 3072

# maximum fps delivered via WebRTC, 0 is for no maximum
max_fps: 25

# password for connecting to stream
password: "neko"

# admin password for connecting to stream
password_admin: "admin"

# default screen resolution and framerate
screen: "1280x720@30"

# limits the pool of ephemeral ports that ICE UDP connections can allocate from
epr: "59000-59100"
```
