### ISSUE TITLE
Internet doesnt seem to be working 

### ISSUE THREAD

**Issue by Teenvan** [m1k1o/neko#206]
I was trying to run the neko app locally but it does not seem to be connected to the internet.  Is there any other setting that needs to be changed ?

I am running this on MacOS 12.6.

I am running the following docker-compose file - 

```yaml
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:chromium"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_SCREEN: '1920x1080@30'
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_NAT1TO1: "<LOCAL-IP ADDRESS FROM SYSTEM PREFS>"
```

![Screenshot 2022-10-08 at 13 18 10](https://user-images.githubusercontent.com/87668092/194707179-33beac2f-9b4c-4307-b571-c1934fc79dfc.png)
