### ISSUE TITLE
black screen when using vaapi with intel gpu

### ISSUE THREAD

**Issue by Yarn** [m1k1o/neko#224]
I'm running docker on an LXD container but I think I have the gpu fully passed through.
The /dev/dri folder is visible within the docker container
```
ls -lh /dev/dri
total 0
crw-rw---- 1 root root 226,   0 Nov 23 03:38 card0
crw-rw-rw- 1 root root 226, 128 Nov 23 03:38 renderD128
```

I tried VLC and firefox with the same result, I don't see anything helpful in the logs for either. These are the logs for VLC.
[neko.log](https://github.com/m1k1o/neko/files/10075103/neko.log)

I installed some packages to try to get things to work, one of the pci ones got rid of an error (not sure which) but none of them changed the result.

**Comment by m1k1o** [comment]
Could you try again with new images?

https://neko.m1k1o.net/#/getting-started/
![image](https://user-images.githubusercontent.com/7534274/229381102-2b789260-99cf-4b31-9d2c-36097348dd4d.png)

**Comment by DX37** [comment]
> Could you try again with new images?
> 
> https://neko.m1k1o.net/#/getting-started/ ![image](https://user-images.githubusercontent.com/7534274/229381102-2b789260-99cf-4b31-9d2c-36097348dd4d.png)

That worked for me, had same issue.

**Comment by Yarn** [comment]
I'm still getting a black screen with no obvious error message. I assume these images have `NEKO_HWENC: VAAPI` by default since it happens with or without that setting now.

**Comment by m1k1o** [comment]
It has been changed to use by default, you can turn it off using `NEKO_HWENC: none`

**Comment by Yarn** [comment]
adding that I get some output about Xorg crashing

The error at the end of the log file `/home/neko/.local/share/xorg/Xorg.99.0.log` inside the container
```
[761391.567] (II) LoadModule: "void"
[761391.567] (WW) Warning, couldn't open module void
[761391.567] (EE) Failed to load module "void" (module does not exist, 0)
[761391.567] (EE) No input driver matching `void'
[761391.567] (II) Falling back to input driver `libinput'
[761391.567] (II) LoadModule: "libinput"
[761391.567] (WW) Warning, couldn't open module libinput
[761391.567] (EE) Failed to load module "libinput" (module does not exist, 0)
[761391.567] (II) LoadModule: "void"
[761391.567] (WW) Warning, couldn't open module void
[761391.567] (EE) Failed to load module "void" (module does not exist, 0)
[761391.567] (EE) No input driver matching `void'
[761391.567] (II) Falling back to input driver `libinput'
[761391.567] (II) LoadModule: "libinput"
[761391.567] (WW) Warning, couldn't open module libinput
[761391.567] (EE) Failed to load module "libinput" (module does not exist, 0)
```

**Comment by hoonlight** [comment]
same issue

**Comment by httpjamesm** [comment]
I'm also still facing this issue with intel-firefox.

```yaml
version: "3.4"
services:
  neko:
    image: "ghcr.io/m1k1o/neko/intel-firefox:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: <redacted>
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
      NEKO_NAT1TO1: 100.100.99.131
      NEKO_HWENC: VAAPI
      LIBVA_DRIVER_NAME: i915
    devices:
      - /dev/dri:/dev/dri
      - /dev/fb0:/dev/fb0
    volumes:
      - '${PWD}/data:/home/neko/.mozilla/firefox/'
      - '${PWD}/policies.json:/usr/lib/firefox/distribution/policies.json'
    container_name: neko
    network_mode: "service:gluetun"
```

Running `vainfo` within the container returns:

```
libva info: VA-API version 1.10.0
libva info: User environment variable requested driver 'i915'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i915_drv_video.so
libva info: va_openDriver() returns -1
vaInitialize failed with error code -1 (unknown libva error),exit
```
