### ISSUE TITLE
Disconnected: peer failed

### ISSUE THREAD

**Issue by Morrowseeer** [m1k1o/neko#227]
I'm running this on Windows 11 with Docker Desktop and I'm using Firefox.

When I use docker-compose with the default docker-compose.yaml file, the server is able to be created and ran, and the webserver works, but whenever I login with the admin password, I just get "Disconnected: peer failed" on the client.

The container itself has logs and includes these:
`2022-12-18 04:02:35,896 DEBG 'neko' stdout output:`
`4:02AM WRN pingAllCandidates called with no candidate pairs. Connection is not possible yet. module=webrtc submodule=pion subsystem=ice`

`4:02AM WRN undeclaredMediaProcessor failed to open SrtcpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc`
`4:02AM WRN undeclaredMediaProcessor failed to open SrtpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc`

Can I get help with this? I have a feeling this could be from Windows.

**Comment by m1k1o** [comment]
If you are accessing it locally, you need to set up your local IP as [NAT1TO1](https://neko.m1k1o.net/#/getting-started/?id=networking) and additional, more info [here](https://neko.m1k1o.net/#/getting-started/troubleshooting).

**Comment by shokohsc** [comment]
Hello, having the same issue with the docker-compose from https://neko.m1k1o.net/#/getting-started/?id=using-mux-instead-of-epr and I was running just fine a few weeks ago in kubernetes, is there a way to get an old docker firefox tag ?

**Comment by m1k1o** [comment]
@shokohsc maybe the issue came with [those recent changes for tcp mux](https://github.com/m1k1o/neko/commit/bd73dfae9d5ad15f738d095744a1f4ebc3ad17b5)? Could you try with reverting that change if it fixes your issue? I can create image for you if needed.

There are versioned images available on [github container registry](https://github.com/m1k1o/neko/pkgs/container/neko%2Ffirefox). But I see they are _very old_ as the pipeline is failing after GPU changes, I should fix that.

**Comment by shokohsc** [comment]
@m1k1o I am having the same behavior with ghcr.io/m1k1o/neko/firefox:2.5 so I guess issue may come from somewhere else. Can you run the latest tag (2.7) on your end without issue (I mean the docker-compose example) ?

**Comment by m1k1o** [comment]
@shokohsc I just took the example docker compose, only added my local IP as NAT1TO1 (because i wanted to test it locally) and it works out of the box.

![image](https://user-images.githubusercontent.com/7534274/208675035-e742e8f4-4ad0-405a-8c1d-47ea01087aee.png)

Check if you have not recently installed some browser extensions that might block WebRTC traffic, e.g. [Private Internet Access](https://chrome.google.com/webstore/detail/private-internet-access/jplnlifepflhkbkgonidnobkakhmpnmh) is known for causing troubles.

**Comment by shokohsc** [comment]
Thanks, I found the issue on my side, sidecar container handling pod network causes the issue for me.

**Comment by m1k1o** [comment]
I pushed version [2.6](https://github.com/m1k1o/neko/pkgs/container/neko%2Ffirefox/59834070?tag=2.6). Can you try?

**Comment by shokohsc** [comment]
oh shoot: `exec /usr/bin/supervisord: exec format error`, by any chance, did you build and push it for arm event for the amd64 arch ?
I build it myself at the 2.6 tag and it runs all right: shokohsc/neko:firefox
So there is definitely an issue between 2.6 & 2.7 but I couldn't find it Oo

**Comment by m1k1o** [comment]
Alright thanks. Zhen github CI is completly unusable and need to be reworked. Created [ticket for that](https://github.com/m1k1o/neko/issues/230).

Could you please try to only revert [this commit](https://github.com/m1k1o/neko/commit/bd73dfae9d5ad15f738d095744a1f4ebc3ad17b5) if it caused the issue? Or alternatively checkout one [commit](https://github.com/m1k1o/neko/commit/cfbda6ec976cfbedbbcab16c5e4384a4bef43552) before [this commit](https://github.com/m1k1o/neko/commit/7d3a888c79c73de709449a4811bcfcceb458e2cd) and try it out there? Maybe upgrade caused that.

Since I am not able to reproduce that, it will be hard to debug. Does it only affect MUX? Only TCP or als UDP?

**Comment by shokohsc** [comment]
Ok, I can run master with [this commit]([this commit](https://github.com/m1k1o/neko/commit/bd73dfae9d5ad15f738d095744a1f4ebc3ad17b5)) reverted.
I cannot seem to be able to build again for the second commit though, I tried the rebuild-server script without success.
Here is my kube manifest:
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neko
  labels:
    app.kubernetes.io/name: neko
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: neko
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neko
    spec:
      automountServiceAccountToken: false
      containers:
        - name: neko
          image: shokohsc/neko:bd73dfa
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Europe/Paris
            - name: NEKO_SCREEN
              value: 1920x1080@60
            - name: NEKO_PASSWORD
              value: neko
            - name: NEKO_PASSWORD_ADMIN
              value: admin
            - name: NEKO_TCPMUX
              value: '8081'
            - name: NEKO_UDPMUX
              value: '8082'
            - name: NEKO_ICELITE
              value: "1"
            - name: NEKO_NAT1TO1
              value: 10.0.42.42
            - name: NEKO_VIDEO_CODEC
              value: "h264"
            - name: NEKO_H264
              value: "1"
            - name: NEKO_IMPLICITCONTROL
              value: "1"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: tcpmux
              containerPort: 8081
              protocol: TCP
            - name: udpmux
              containerPort: 8082
              protocol: UDP
          startupProbe:
            tcpSocket:
              port: http
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 2
              gpu.intel.com/i915: 1
              memory: 4096M
            requests:
              cpu: 1
              gpu.intel.com/i915: 1
              memory: 2048M
```
