### ISSUE TITLE
Connection Terminates. Don't know how to make sense of what is happening

### ISSUE THREAD

**Issue by phere-x** [m1k1o/neko#233]
Here's my docker-compose

```
  nek:
    container_name: nek1
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1280x720@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: ater902
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
```

Here are the `docker logs` https://pastebin.com/EgZ8y9k7
