### ISSUE TITLE
Issue: Unable to log in.

### ISSUE THREAD

**Issue by DvidPiDev** [m1k1o/neko#270]
Hey! 

I just set up n.eko and I find myself stuck on the login. 
I left the login as the default one (user: admin password: neko) but whenever I use those credentials, I just get stuck on the circle expanding through the circle (loading)
![image](https://user-images.githubusercontent.com/79283415/229280135-f3f9c701-b077-4d8f-8402-8b6cd147bff4.png)

I already tried restarting and redeploying. Here is my docker-compose:
```
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
```
