### ISSUE TITLE
can I use CDN to speed up

### ISSUE THREAD

**Issue by tanglu1323123** [m1k1o/neko#349]
Hi,
I want to use cdn(cdn support websocket) to hide my vps, which is running neko.
But I failed, it shows `disconnected connection timeout` , I don't know why.

And I noticed that the video will use udp and the port default is '52000-52100' , it seems that the video can't be speed up by cdn .

**Comment by tanglu1323123** [comment]
this is my docker compose yaml

```
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox"		
    restart: "unless-stopped"
    shm_size: "10gb"
    ports:
      - "8080:8080"		
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30	
      NEKO_PASSWORD: neko		
      NEKO_PASSWORD_ADMIN: admin	
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
```
