### ISSUE TITLE
Inaccessible outside of LAN

### ISSUE THREAD

**Issue by uhidontkno** [m1k1o/neko#366]
Connecting to my Neko session over Neko Rooms, setting NAT1TO1 to my external IP address, all the UDP ports are opened, the frontend TCP port is opened.... just sits on a green circle.

**Comment by yesBad** [comment]
Sadly this really doesn't tell us anything...

**Comment by uhidontkno** [comment]
I'm trying to connect to my Neko instance, going to the URL, and logging in... just hangs on a green circle. My `docker-compose.yml` file:
```
services:
  neko-rooms:
    image: "m1k1o/neko-rooms:latest"
    restart: "unless-stopped"
    environment:
      - "TZ=America/New_York"
      - "NEKO_ROOMS_MUX=true"
      - "NEKO_ROOMS_EPR=59000-59100" // 59000-59100 are open over tcp AND udp
      - "NEKO_ROOMS_NAT1TO1=108.86.__.__" # IP address of your server that is reachable from client
      - "NEKO_ROOMS_INSTANCE_URL=http://bak-ba_____.deblok.me/" # external URL
      - "NEKO_ROOMS_INSTANCE_NETWORK=neko-rooms-net"
      - "NEKO_ROOMS_TRAEFIK_ENABLED=false"
      - "NEKO_ROOMS_PATH_PREFIX=/i/"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Am I doing something wrong? The WebSockets connection was made, but I'm assuming something is wrong with the UDP or WebRTC connection.
