### ISSUE TITLE
CDP port not getting forwarded to host

### ISSUE THREAD

**Issue by vkWeb** [m1k1o/neko#377]
Hi @m1k1o, thanks for maintaining this amazing piece of tech. We are planning to use it for our product @ QAmom.com.

We will be eventually deploying the neko's chromium browser to AWS EC2 if things work out well. But before that, I am testing it out locally. We have tried Hyperbeam, Kasm and BrowserBox. When we landed to Neko, we were impressed by its extensionibility. We can tweak a lot of stuff.

So, we want to control the browser via CDP from our backend. We enabled developer tools in policies.json, we added `--remote-debugging-port=9222` flag to the command on supervisord.conf. And we are forwarding the port on docker compose as well. Visiting 127.0.0.1:9222/json inside neko container works but from my host its not working. 

What's going wrong here? Below are relevant files for you to see.  

`policies.json`
```json
{
    "AutofillAddressEnabled": false,
    "AutofillCreditCardEnabled": false,
    "BrowserSignin": 0,
    "DefaultNotificationsSetting": 2,
    "DeveloperToolsAvailability": 0, /* Enabling dev tools. */
    "EditBookmarksEnabled": false,
    "FullscreenAllowed": true,
    "IncognitoModeAvailability": 1,
    "SyncDisabled": true,
    "AutoplayAllowed": true,
    "BrowserAddPersonEnabled": false,
    "BrowserGuestModeEnabled": false,
    "DefaultPopupsSetting": 2,
    "DownloadRestrictions": 3,
    "VideoCaptureAllowed": true,
    "AllowFileSelectionDialogs": false,
    "PromptForDownloadLocation": false,
    "BookmarkBarEnabled": false,
    "PasswordManagerEnabled": false,
    "BrowserLabsEnabled": false,
    "URLAllowlist": [
        "file:///home/neko/Downloads"
    ],
    "URLBlocklist": [
        "file://*",
        "chrome://policy"
    ],
    "ExtensionInstallForcelist": [],
    "ExtensionInstallAllowlist": [],
    "ExtensionInstallBlocklist": [
        "*"
    ]
}
```

`supervisord.conf`
```
[program:chromium]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/chromium
  --remote-debugging-port=9222  /* CDP port. */
  --window-position=0,0
  --display=%(ENV_DISPLAY)s
  --user-data-dir=/home/neko/.config/chromium
  --no-first-run
  --start-maximized
  --bwsi
  --force-dark-mode
  --disable-file-system
  --disable-gpu
  --disable-software-rasterizer
  --disable-dev-shm-usage
stopsignal=INT
autorestart=true
priority=800
user=%(ENV_USER)s
stdout_logfile=/var/log/neko/chromium.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
redirect_stderr=true

[program:openbox]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s"
command=/usr/bin/openbox --config-file /etc/neko/openbox.xml
autorestart=true
priority=300
user=%(ENV_USER)s
stdout_logfile=/var/log/neko/openbox.log
stdout_logfile_maxbytes=100MB
stdout_logfile_backups=10
redirect_stderr=true
```

`docker-compose.yml` ("chromvium:latest" is name of our custom image that we created by changing above settings)
```
version: "3.4"
services:
  neko:
    image: "chromvium:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "8081:8081/tcp"
      - "8082:8082/udp"
      - "9523:9222"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_SCREEN: '800x600@60'
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_TCPMUX: 8081
      NEKO_UDPMUX: 8082
      NEKO_ICELITE: 1
      NEKO_NAT1TO1: 127.0.0.1

```
