### ISSUE TITLE
Multiarch images

### ISSUE THREAD

**Issue by clementgineste** [m1k1o/neko#394]
DH & GHCR don't seem to support multiarch for Neko, I found separate images do and I checked the GH Actions workflow and it adds an “arm” prefix. 
Wouldn't it be more logical and practical to use the same image name with the different architectures available?

The goal for me is to put something like ghcr.io/neko:firefox and get the right image for AMD64 and ARM64 with the same compose file.

++

**Comment by m1k1o** [comment]
Yes, that would be really great to have. But we have different dockerfiles for different architectures because of the complexity of the environment. At the time of writing the CI/CD there was no support (or just i was not able to find a way) for this in docker buildx.

PR to rework CI/CD to support this functionality are welcome, maybe things habe changed over the years.

**Comment by clementgoclock** [comment]
I started to look into .docker and GHA workflows, i see there is a base image used as base (hihi) for later images and a lot of version for intel or other thing.
Nowadays to generate an image multiarch [it's pretty simple](https://docs.docker.com/build/ci/github-actions/multi-platform/) : 
```
     - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: user/app:latest
```
How's the overhead for different image (VAAPI/Nvidia, ..) ? Could it be reunite in one image for the sake of simplicity ?

Anyway if i'll find time i'll try to make something and upgrade action version at the same time. Is every Dockerfile up to date ?
