### ISSUE TITLE
Default login not working. Peer failed

### ISSUE THREAD

**Issue by TrackLab** [m1k1o/neko#406]
No matter if using "neko" or "admin" as password, I get the error "Peer Failed". Using other passwords immedietly results in the website saying wrong password.
So I am not exactly sure what to do here.

**Comment by m1k1o** [comment]
Please take a look at [troubleshooting guide](https://neko.m1k1o.net/#/getting-started/troubleshooting). Seems like an isssue with WebRTC or Port Forward / Network.

**Comment by Togtja** [comment]
Hi, I'm facing similar problems.
I am running Neko on an Ubuntu 22.04 Server on my network, I have not port forwarded any ports or such as it's all locally.

I tried both the firefox and VLC docker images

I am getting the same problems, I tried both Firefox and Chrome browsers (Same error on both vlc and firefox image)
From the `chrome://webrtc-internals/` I get this

![image](https://github.com/user-attachments/assets/6f5b78a6-f27e-4fe7-aecb-19e2585ae3ea)
Basically the error
`connectionstatechange
failed`


From the docker I get these warnings when I boot up (VLC or Firefox)
```
neko_1  | 11:49AM WRN preflight complete without config file config= debug=false logging=false
neko_1  | 11:49AM WRN http listening on :8080 module=http
```
And these when I connect with correct password on the VLC image
```
 11:38AM WRN peer failed id=PuzSwhPNVZjmYDXGb-OtjDMzVsvyyQTP module=webrtc
neko_1  | 11:38AM WRN Failed to discover mDNS candidate 8283905d-7971-417f-8d2c-70dc83298502.local: mDNS: connection is closed module=webrtc submodule=pion subsystem=ice
neko_1  | 11:38AM WRN Failed to start manager: connecting canceled by caller module=webrtc submodule=pion subsystem=pc
neko_1  | 11:38AM WRN Failed to start SCTP: DTLS not established module=webrtc submodule=pion subsystem=pc
neko_1  | 11:38AM WRN undeclaredMediaProcessor failed to open SrtcpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc
neko_1  | 11:38AM WRN undeclaredMediaProcessor failed to open SrtpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc
```
And these with firefox image: (Note I get a single error)
```
neko_1  | 11:51AM WRN negotiation is needed module=webrtc
neko_1  | 11:51AM ERR creating offer failed error="InvalidModificationError: invalid proposed signaling state transition: have-local-offer->SetLocal(offer)->have-local-offer" module=webrtc
neko_1  | 11:51AM WRN peer failed id=10L6DImmOgkkX70Tt0-fsf_iZob9sbgy module=webrtc
neko_1  | 11:51AM WRN Failed to discover mDNS candidate 62a91d9f-c144-49c0-b205-589848e7b28a.local: mDNS: connection is closed module=webrtc submodule=pion subsystem=ice
neko_1  | 11:51AM WRN Failed to start manager: connecting canceled by caller module=webrtc submodule=pion subsystem=pc
neko_1  | 11:51AM WRN Failed to start SCTP: DTLS not established module=webrtc submodule=pion subsystem=pc
neko_1  | 11:51AM WRN undeclaredMediaProcessor failed to open SrtcpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc
neko_1  | 11:51AM WRN undeclaredMediaProcessor failed to open SrtpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc
```


My Docker compose, the only diffrence is I change firefox to vlc when trying out the vlc
```yaml
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
  ```
