### ISSUE TITLE
Reversed Proxy with Apache unable to connect externally

### ISSUE THREAD

**Issue by Togtja** [m1k1o/neko#410]
I am trying to use the neko server behind a reverse proxy, but I am having some issues with the websocket connection.
I am able to connect to the server, but it gives peer failed when I try to login.
It works perfectly when I connect to the domain on the local network where the domain and the server are hosted.

Note that the domain is hosted on a different server than the neko server. Hence the private IP address in the configuration instead of localhost.

My apache2 configuration for a reverse proxy:

```conf
<IfModule mod_ssl.c>
<VirtualHost *:443>
    ServerName neko.domain.com

    ErrorLog ${APACHE_LOG_DIR}/neko_error.log
    CustomLog ${APACHE_LOG_DIR}/neko_access.log combined

    LoadModule proxy_module /usr/lib/apache2/modules/mod_proxy.so
    LoadModule proxy_http_module /usr/lib/apache2/modules/mod_proxy_http.so
    LoadModule proxy_wstunnel_module /usr/lib/apache2/modules/mod_proxy_wstunnel.so

    SSLEngine on
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off

    ProxyRequests Off
    ProxyPass / http://192.168.1.183:8080/
    ProxyPassReverse / http://192.168.1.183:8080/
    RewriteEngine on
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteCond %{HTTP:Connection} upgrade [NC]
    RewriteRule ^/?(.*) "ws://192.168.1.183:8080/$1" [P,L]

    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /etc/letsencrypt/live/neko.domain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/neko.domain.com/privkey.pem
</VirtualHost>
</IfModule>
```

My neko configuration:

```yaml

services:
  neko:
    image: "m1k1o/neko:vlc"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: password
      NEKO_PASSWORD_ADMIN: admin_password
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
      NEKO_NAT1TO1: 192.168.1.183

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.neko-frontend.loadbalancer.server.port=8080"
      - "traefik.http.routers.neko.rule=Host(`neko.domain.com`)"
      - "traefik.http.routers.neko.entrypoints=web-secure"
      - "traefik.http.routers.neko.tls.certresolver=letsencrypt"

```

When an external ip connect the docker output  `WRN` or  higher I see is:
```
neko-1  | 8:45AM WRN negotiation is needed module=webrtc
neko-1  | 8:45AM ERR creating offer failed error="InvalidModificationError: invalid proposed signaling state transition: have-local-offer->SetLocal(offer)->have-local-offer" module=webrtc
neko-1  | 8:45AM WRN read message error error="websocket: close 1005 (no status)" module=websocket
neko-1  | 8:45AM WRN Failed to discover mDNS candidate c5bdabf4-7e3d-4b0f-af83-47c6b9c0edae.local: mDNS: connection is closed module=webrtc submodule=pion subsystem=ice
neko-1  | 8:45AM WRN Failed to start manager: connecting canceled by caller module=webrtc submodule=pion subsystem=pc
neko-1  | 8:45AM WRN Failed to start SCTP: DTLS not established module=webrtc submodule=pion subsystem=pc
neko-1  | 8:45AM WRN undeclaredMediaProcessor failed to open SrtcpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc
neko-1  | 8:45AM WRN undeclaredMediaProcessor failed to open SrtpSession: the DTLS transport has not started yet module=webrtc submodule=pion subsystem=pc

```
In the firefox browser trying to connect I get a peer failed error

Any clue as to what might be wrong, or if anything in my configurations is off?
