### ISSUE TITLE
Failed to read from candidate tcp4 host xyz:443: io: read/write on closed pipe module=webrtc submodule=pion subsystem=ice

### ISSUE THREAD

**Issue by cedricbieder** [m1k1o/neko#443]
Hi.

I am setting up a neko behind a firewall with this config:

```
version: '3.4'
services:
  app-stream:
    image: "m1k1o/neko:firefox"
    restart: unless-stopped
    shm_size: 2gb
    ports:
      - '8080:8080'
      - '443:443'
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: UIefne8Nk4ecwx2
      NEKO_PASSWORD_ADMIN: drsgvneru34vnusv
      NEKO_TCPMUX: 443
#      NEKO_EPR: 443
      NEKO_NAT1TO1: xyz
#      NEKO_IMPLICIT_CONTROL: true
      NEKO_FILE_TRANSFER: true
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    container_name: neko_youtube
```

I expose the Port 443 to my network and call the website. I see the login dialog and enter my login credentials, in the console I see that the websocket sends information about the xyz domain and the 443 port. But the login still ends in a timeout. 

The neko log say:

`
Failed to read from candidate tcp4 host xyz:443: io: read/write on closed pipe module=webrtc submodule=pion subsystem=ice
`

With a nmap I can reach xyz:443 from the neko host and my firewalls allows the connection on both ends. 

1. What can be the problem here?
2. Why does the neko server has to reach the xyz. In my understanding, xyz is there that the client request are forwarded to the internal neko.

Please let me know if you need more information or if you got my problem :].

Thank you for your work and help.

best cedric
