### ISSUE TITLE
Unable to control using mouse/keyboard

### ISSUE THREAD

**Issue by Kristoffeh** [m1k1o/neko#452]
Hello.

I have to say i am impressed with this project, great stuff! Though I have been struggling with an issue for quite a few hours now, i think i went through all the documentation on the [website](https://neko.m1k1o.net/#/?id=neko). The problem i am facing is that i can't control the session with mouse and keyboard, this is an issue since i was planning to use when i show web-related stuff to my co-workers.

I am able to lock the room, lock controls etc. I did have a few attempts with environment variables without luck, and now i am just stuck. Is there a dependency needed for mouse/keyboard controls to work?

As recommended in the docs, i run it inside docker. Here's my configuration:

```
services:
  neko:
    container_name: "Neko"
    image: "m1k1o/neko:chromium"
    restart: "unless-stopped"
    shm_size: "2gb"
    cap_add:
      - SYS_ADMIN
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: '1280x720@30'
      NEKO_PASSWORD: qwe123
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_NAT1TO1: 192.168.113.16                  # this is the ip of the VM
      PION_ICE_MULTICASTDNSMODE: queryonly
      NEKO_ICELITE: true
      NEKO_VIDEO_CODEC: h264
      #NEKO_ICE_DISABLE_RELAY: true
      #NEKO_ALLOW_CONTROL: true
      NEKO_ALLOW_KEYBOARD: true
      NEKO_ALLOW_MOUSE: true
      #NEKO_CONTROL_PROTECTION: false
```

Once i know that this piece of software suites my needs, i will supply it with a reverse proxy as i have done with my other services. Currently it just runs locally on my HomeLab.

My session looks like this, everything else seem to be working fine. I just cannot control it.

![image](https://github.com/user-attachments/assets/cdb15588-1f7f-43de-a3d5-1ff48fb0e1f7)
