### ISSUE TITLE
Rtmp broadcast ends in blackscreen

### ISSUE THREAD

**Issue by cedricbieder** [m1k1o/neko#465]
Hi again,

I try to set up a broadcast with a simple neko config:

```
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_BROADCAST_URL: "rtmp://mylocalip:1935/live/stream"
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_IMPLICIT_CONTROL: true
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1

```
and tiangolo/nginx-rtmp
```
version: "3.4"
services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "8888:80"
      - "8443:443"
    volumes:
      - ./nginx-config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-config/certs/fullchain.pem:/etc/nginx/fullchain.pem
      - ./nginx-config/certs/privkey.pem:/etc/nginx/privkey.pem
# ./nginx-config/certs/nginx-selfsigned.key:/etc/nginx/certs/nginx-selfsigned.key:ro

  nginx-rtmp:
    image: tiangolo/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"     # RTMP Port
      - "8111:80"       # HTTP Port für Videoausgabe
    volumes:
      - ./nginx-config/nginx-rtmp.conf:/etc/nginx/nginx.conf
      - ./recordings:/var/www/html/recordings  # Speicherort für Aufnahmen
      - ./log:/var/log/nginx
      - ./hls:/var/www/html/hls
    environment:
      - PUID=65534       # Setze die User-ID
      - PGID=65534       # Setze die Group-ID

```
But the video I get are just black. I also tested with. 

```
ffmpeg -i rtmp://mylocalip:1935/live/stream -t 20 -c copy output2.mp4
```

but these videos are also black. Did somebody have similar problems, or a quick idea what is going wrong?

Thank you for some help :)
