### ISSUE TITLE
No internet when using Google-Chrome but I do have access to the internet from the container

### ISSUE THREAD

**Issue by Nivg** [m1k1o/neko#466]
Hi @m1k1o 

Thanks for this amazing project!

I am using the base google-chrome composer:
```
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:google-chrome"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "8081:8081/tcp"
      - "8082:8082/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_TCPMUX: 8081
      NEKO_UDPMUX: 8082
      NEKO_ICELITE: true
      NEKO_NAT1TO1: [my_local_ip_address]
      NEKO_DEBUG: 1
    cap_add:
      - SYS_ADMIN # required for google-chrome
```

entering the Neko server without issues, but no internet access from inside the browser.

I have entered the container via bash and no issues when pinging 8.8.8.8 or any other domain/ip for that matter.

I'm using MacOS (15.2).

I see a lot of those issues:
```
neko-1  | 2025-01-19 12:03:22,107 DEBG 'google-chrome' stdout output:
neko-1  | [11:95:0119/120322.107588:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
neko-1  | [11:95:0119/120322.107616:ERROR:bus.cc(407)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

note that using the firefox container I have no issues with the same basic settings.
