### ISSUE TITLE
Cannot interact with mouse

### ISSUE THREAD

**Issue by pippo73** [m1k1o/neko#469]
Hello all, 
I've installed a basic installation on a docker container with the following configuration:

```
services:
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    volumes:
      - ~/Neko/Firefox:/home/neko/.mozilla/firefox # persist firexfox settings
    environment:
      NEKO_SCREEN: '1920x1080@30'
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
#      NEKO_NAT1TO1: <your-IP>

```

and the start seems working, but when I try to interact with the page nothing happens.

![Image](https://github.com/user-attachments/assets/08dd6471-d93b-49f8-9995-f429d3f6f726)

I cannot move the mouse, so I cannot do anything more. I've logged in with neko and admin password but nothing changes :-( 
Do I miss something.

If it could be a problema. I'm accessing to the webpage trought cloudflare tunnel
