### ISSUE TITLE
How to force neko container to run browser in kiosk mode locked on 1 site?

### ISSUE THREAD

**Issue by chelaxian** [m1k1o/neko#478]
How to force neko container to run browser in kiosk mode locked on 1 site?
I tried this config but with no luck. Neko is opens with default page as normal.

```yaml
cat docker-compose.yaml
version: "3.4"

networks:
  restricted_net:
    external: true

services:
  neko:
    networks:
      - restricted_net
    image: "ghcr.io/m1k1o/neko/arm-chromium:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 640×512@60
      #NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: neko
      NEKO_EPR: 52000-52100
      #NEKO_IMPLICIT_CONTROL: "true"
      NEKO_FILE_TRANSFER_ENABLED: "false"
      NEKO_ICELITE: 1
      #NEKO_NAT1TO1: 10.14.0.4
      NEKO_IPFETCH: "http://checkip.amazonaws.com"
      NEKO_LOCKS: file_transfer
      NEKO_CMD: "chromium-browser --app=https://www.youtube.com/?app=desktop --kiosk --force-dark-mode"
      #ENV_USER: "neko"
      #ENV_DISPLAY: ":0"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./policies.json:/etc/chromium/policies/managed/policies.json
      - ./preferences.json:/etc/chromium/policies/managed/preferences.json

```
