### ISSUE TITLE
Disconnected after migration to v3

### ISSUE THREAD

**Issue by alanmilinovic** [m1k1o/neko#500]
So I migrated my configuration and it all stopped working. I get red notification disconnected. It all normally worked before. 

```
version: "3.4"
services:
  neko:
    image: "ghcr.io/m1k1o/neko/google-chrome:latest"
    shm_size: "2gb"
    ports:
      - "8081:8081"
      - "20532:20532/tcp"
      - "20532:20532/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_DESKTOP_SCREEN: '1280x720@30'
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: guest
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: admin
      NEKO_SERVER_BIND: :8081
      NEKO_WEBRTC_TCPMUX: 20532
      NEKO_WEBRTC_UDPMUX: 20532
      NEKO_WEBRTC_ICELITE: 1
      NEKO_FILE_TRANSFER_ENABLED: 1
      NEKO_SESSION_LOCKED_CONTROLS: 1
      NEKO_SESSION_IMPLICIT_HOSTING: 1
      NEKO_LEGACY: 0
    volumes:
      - ${PWD}/data:/home/neko/.config/google-chrome
      - ${PWD}/policies.json:/etc/opt/chrome/policies/managed/policies.json
    restart: unless-stopped
```

Tried adding 'NEKO_WEBRTC_NAT1TO1' with the host ip but still the same, also I haven't used it before also.
