### ISSUE TITLE
Defining Multiple Member Providers Breaks Authentication

### ISSUE THREAD

**Issue by lbrauns** [m1k1o/neko#505]
Hi,

I tried to define multiple Member Providers in the config.yaml and well, this seems to fully break authentication and authorization. It is probably not intended to work anyways, but you should still know. 

The configuration is:

````
member:
  - provider: file
    file:
    # Absolute path to the file containing the users and their passwords.
      path: /opt/neko/members.json
    # Whether the passwords are hashed using sha256 or not.
      hash: false
  - provider: multiuser
    multiuser:
      admin_password: "admin3"
      admin_profile:
        name: "admin" # if empty, the login username is used
        is_admin: true
        can_login: true
        can_connect: true
        can_watch: true
        can_host: true
        can_share_media: true
        can_access_clipboard: true
        sends_inactive_cursor: true
        can_see_inactive_cursors: true
      user_password: "neko"
      user_profile:
        name: "" # if empty, the login username is used
        is_admin: false
        can_login: true
        can_connect: true
        can_watch: true
        can_host: false
        can_share_media: false
        can_access_clipboard: false
        sends_inactive_cursor: false
        can_see_inactive_cursors: false
````

With this configuration i can login with any username and any password and will always be signed in as an administrator.
