### ISSUE TITLE
WebSocket does not send pings in v3, causes reconnects when using default nginx config

### ISSUE THREAD

**Issue by lbrauns** [m1k1o/neko#506]
Hi, 

since watchtower updated my neko firefox instance me and the users of the browser experience sudden reconnects. The reconnect is seamless and lasts like a second but becomes quite annoying, especially if users did not disable the chatsounds and get a notification that somebody joined... 

I can't really figure out what is happening there... So I enabled trace logging and hope somebody can give me a hint what is happening.

Relevant information: Neko is hosted behind an nginx-proxy-manager. The UDP ports for WebRTC are exposed directly, so it shouldn't really be relevant it guess.

**Logfile**

I think the relevant error in the log is `1:00PM ERR websocketproxy: Error when copying from client to backend: %v error="websocket: close 1006 (abnormal closure): unexpected EOF" module=legacy` 

For completeness, the full logfile is attached as a file (it's too big to paste in the comment).

[neko-disconnect.log](https://github.com/user-attachments/files/19621502/neko-disconnect.log)

**Config**

I tried to migrate the config to the new v3 config. For some reason, if i set `NEKO_LEGACY: false` the connection after the sign-in times out. As  far as I can see I am not using an legacy config anymore... 

docker-compose.yml
```
services:
  neko:
    image: "ghcr.io/m1k1o/neko/firefox:latest"
    restart: "unless-stopped"
    shm_size: "6gb"
    ports:
      - "52000-52100:52000-52100/udp"
    volumes:
      - ./firefox:/home/neko/.mozilla/firefox # persist firexfox settings
      - ./config.yaml:/opt/neko/config.yaml
      - ./policies.json:/usr/lib/firefox/distribution/policies.json
      - ./neko.js:/usr/lib/firefox/mozilla.cfg
      - ./members.json:/opt/neko/members.json
      - ./log:/opt/neko/log/
    environment:
      NEKO_DESKTOP_SCREEN: '1920x1080@30'
      NEKO_WEBRTC_EPR: 52000-52100
      NEKO_WEBRTC_ICELITE: 1
      NEKO_WEBRTC_NAT1TO1: <SERVER IP>
      NEKO_CONFIG: /opt/neko/config.yaml
      NEKO_LEGACY: true
networks:
  default:
    external: true
    name: nginx
```

config.yaml:

```
server:
  bind: "127.0.0.1:8080"
  proxy: true
session:
  cookie:
    enabled: false
  private_mode: false
  locked_logins: false
  locked_controls: true
  control_protection: true
  implicit_hosting: false
  inactive_cursors: true
  merciful_reconnect: false
  heartbeat_interval: 120
log:
  dir: /opt/neko/log
  json: false
  #level: "info"
  level: "trace"
  nocolor: false
  time: "unix"
plugins:
  enabled: false
member:
  #- provider: file
  #  file:
  #  # Absolute path to the file containing the users and their passwords.
  #    path: /opt/neko/members.json
  #  # Whether the passwords are hashed using sha256 or not.
  #    hash: false
  - provider: multiuser
    multiuser:
      admin_password: "<ADMIN PASSWORD>"
      admin_profile:
        name: "admin" # if empty, the login username is used
        is_admin: true
        can_login: true
        can_connect: true
        can_watch: true
        can_host: true
        can_share_media: true
        can_access_clipboard: true
        sends_inactive_cursor: true
        can_see_inactive_cursors: true
      user_password: "<USER PASSWORD>"
      user_profile:
        name: "" # if empty, the login username is used
        is_admin: false
        can_login: true
        can_connect: true
        can_watch: true
        can_host: false
        can_share_media: false
        can_access_clipboard: false
        sends_inactive_cursor: false
        can_see_inactive_cursors: false
```
