### ISSUE TITLE
ExtensionSettings installation_mode `allowed` ignored

### ISSUE THREAD

**Issue by DaWe35** [m1k1o/neko#512]
Hi, I've tried everything, but I could't get Firefox to let users install addons. I've spent almost 2 hours trying to solve this and I have no more ideas.

`docker-compose.json`:
```
services:
  neko:
    image: "ghcr.io/m1k1o/neko/firefox:latest"
    restart: "no"
    shm_size: "2gb"
    volumes:
      - "./policy.json:/usr/lib/firefox/distribution/policies.json"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_DESKTOP_SCREEN: 1920x1080@30
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: mypasswd
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: mypasswd2
      NEKO_WEBRTC_EPR: 52000-52100
      NEKO_WEBRTC_ICELITE: 1
```

`policy.json`:

```
{
    "policies": {
      "BlockAboutAddons": false,
      "BlockAboutConfig": false,
      "BlockAboutProfiles": true,
      "BlockAboutSupport": true,
      "Bookmarks": [
        {
          "Title": "IPLeak",
          "URL": "https://ipleak.net/",
          "Favicon": "https://ipleak.net/favicon.ico",
          "Folder": "Pages",
          "Placement": "toolbar"
        },
        {
          "Title": "YouTube",
          "URL": "https://www.youtube.com/",
          "Favicon": "https://www.youtube.com/favicon.ico",
          "Folder": "Pages",
          "Placement": "toolbar"
        },
        {
          "Title": "Google",
          "URL": "https://www.google.com/",
          "Favicon": "https://www.google.com/favicon.ico",
          "Folder": "Pages",
          "Placement": "toolbar"
        }
      ],
      "CaptivePortal": false,
      "DisableAppUpdate": false,
      "DisableBuiltinPDFViewer": false,
      "DisableDeveloperTools": false,
      "DisableFeedbackCommands": true,
      "DisableFirefoxAccounts": true,
      "DisableFirefoxScreenshots": false,
      "DisableFirefoxStudies": true,
      "DisableForgetButton": true,
      "DisableMasterPasswordCreation": true,
      "DisablePocket": true,
      "DisablePrivateBrowsing": true,
      "DisableProfileImport": true,
      "DisableProfileRefresh": true,
      "DisableSafeMode": true,
      "DisableSetDesktopBackground": true,
      "DisableSystemAddonUpdate": true,
      "DisableTelemetry": true,
      "DisplayBookmarksToolbar": false,
      "DontCheckDefaultBrowser": true,
      "EnableTrackingProtection": {
        "Cryptomining": true,
        "Fingerprinting": true,
        "Value": true
      },
      "ExtensionSettings": {
        "*": {
          "installation_mode": "allowed"
        },
        "uBlock0@raymondhill.net": {
          "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi",
          "installation_mode": "force_installed"
        }
      },
      "ExtensionUpdate": true,
      "FirefoxHome": {
        "Highlights": false,
        "Pocket": false,
        "Search": true,
        "Snippets": false,
        "TopSites": true
      },
      "FlashPlugin": {},
      "HardwareAcceleration": false,
      "Homepage": {
        "Additional": [],
        "StartPage": "previous-session"
      },
      "NewTabPage": true,
      "NoDefaultBookmarks": true,
      "OfferToSaveLogins": false,
      "OfferToSaveLoginsDefault": false,
      "OverrideFirstRunPage": "",
      "OverridePostUpdatePage": "",
      "PasswordManagerEnabled": false,
      "Permissions": {
        "Camera": {
          "BlockNewRequests": true
        },
        "Location": {
          "BlockNewRequests": true
        },
        "Microphone": {
          "BlockNewRequests": true
        },
        "Notifications": {
          "BlockNewRequests": true
        }
      },
      "Preferences": {
        "browser.tabs.warnOnClose": false,
        "browser.urlbar.suggest.bookmark": false,
        "browser.urlbar.suggest.history": false,
        "browser.urlbar.suggest.openpage": false,
        "datareporting.policy.dataSubmissionPolicyBypassNotification": true,
        "dom.disable_window_flip": true,
        "dom.disable_window_move_resize": true,
        "dom.event.contextmenu.enabled": true,
        "extensions.getAddons.showPane": false,
        "places.history.enabled": false,
        "privacy.file_unique_origin": true,
        "ui.key.menuAccessKeyFocuses": false,
        "browser.tabs.allowTabDetach": false
      },
      "PromptForDownloadLocation": false,
      "SanitizeOnShutdown": false
    }
  }
  
```
