### ISSUE TITLE
keyboard input not working after PR 522

### ISSUE THREAD

**Issue by vincentchu37** [m1k1o/neko#523]
Using the latest firefox docker image created from PR #522, keyboard input no longer seems to work, mouse works fine still

Build and Push to Docker Hub #220: Commit [f145bd5](https://github.com/m1k1o/neko/commit/f145bd58c9d767307a285f2c1eb4e498ba4c6cd6) pushed by [m1k1o](https://github.com/m1k1o)

Reverting to 3.0.4 seems to resolve the issue. 

```
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    container_name: neko
    shm_size: "4gb"
    volumes:
      - ./policies.json:/usr/lib/firefox/distribution/policies.json
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_MEMBER_PROVIDER: noauth
      NEKO_SESSION_HEARTBEAT_INTERVAL: 30
      NEKO_TCPMUX: 52000
      NEKO_UDPMUX: 52000
      NEKO_ICELITE: 1
      NEKO_PROXY: true

```
