### ISSUE TITLE
Need help to build a minimal web embed for KIOSK

### ISSUE THREAD

**Issue by iamshouvikmitra** [m1k1o/neko#544]
Is there a possibility where I can hide the URL browser skin, and restrict it to a specific domain / website?

My goal is to be able to embed the browser page in my application to achieve something like browserbase/openai operator. Need your suggestions and ideas on how we can achieve this goal. All ideas (big or small) are welcome!

**Comment by m1k1o** [comment]
Use `?embed=1` in the URL with `--kiosk` flag in the google chrome. See docs: https://neko.m1k1o.net/docs/v3/customization/ui#query-parameters

**Comment by iamshouvikmitra** [comment]
Thank you so much @m1k1o for the guidance. I understand the query parameter customization now. Can you please help me on how I can use the `--kiosk` flag to startup chrome or firefox inside neko? 

Here is my docker-compose.yaml file
```
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:firefox"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8080:8080"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: abcd
      NEKO_PASSWORD_ADMIN: abcdxyz
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
      NEKO_UNPRIV_FILE_TRANSFER: true
      NEKO_FILE_TRANSFER_ENABLED: true
```
