### ISSUE TITLE
Stuck on loading screen how to fix? :(

### ISSUE THREAD

**Issue by enough-jainil** [m1k1o/neko#546]
![Image](https://github.com/user-attachments/assets/db3d3e94-d637-46df-8917-3644e271f308)

```
services:
  neko:
    image: ghcr.io/m1k1o/neko/firefox:latest
    restart: unless-stopped
    shm_size: 4gb
    ports:
      - 8080:8080
      - 52000-52100:52000-52100/udp
    environment:
      NEKO_DESKTOP_SCREEN: 1920x1080@30
      NEKO_MEMBER_MULTIUSER_USER_PASSWORD: neko
      NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD: neko
      NEKO_WEBRTC_EPR: 52000-52100
      NEKO_WEBRTC_ICELITE: 1
networks: {}
```
