### ISSUE TITLE
[BUG] Opera doesn't work as expected with n.eko

### ISSUE THREAD

**Issue by RisedSky** [m1k1o/neko#74]
![image](https://user-images.githubusercontent.com/23197999/122285275-ce15b700-ceee-11eb-81a1-384fb29ca6f4.png)

The same server, is working on Firefox and Chrome, but not Opera

Tested on Opera version 76.0.4017.177 and 77.0.4054.80

**Comment by m1k1o** [comment]
I tested this only on latest Chromium (Google Chrome, Edge), Firefox and Safari. Never tried Opera. Dont see it even listed on this page: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/WebRTC_codecs#supported_video_codecs

**Comment by mbattista** [comment]
Can you share your configuration? Did you use H264 or VP8?

With H264 I can connect with opera but get a black screen. With VP8 it works seamlessly.
I also checked the following browsers (on Linux): Chrome, Chromium, Firefox, Opera, Vivaldi, Vieb, Edge (Beta)
![browsers](https://user-images.githubusercontent.com/26247314/122636277-adb14c80-d0e8-11eb-8efb-1e8f7495ce6d.png)

**Comment by RisedSky** [comment]
I don't understand what's happening, i'm just having a peer disconnected, but it's working on chrome and firefox, so i don't really know....

**Comment by mbattista** [comment]
If you share your `docker-compose.yml` and some details of your setup, we can try to reproduce the error and help you.

E.g. perhaps there **could** be a bug how Opera handels 1to1-Nat or ICELite.

**Comment by RisedSky** [comment]
Docker compose :

```
version: "3.4"
services:
  neko:
    image: "m1k1o/neko:ungoogled-chromium"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "9090:8080"
      - "52000-52100:52000-52100/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_SCREEN: '1280x720@30'
      NEKO_PASSWORD: 
      NEKO_PASSWORD_ADMIN: 
      NEKO_EPR: 52000-52100
```
